<nav>
	<ul>
		<li><?=anchor('/','Главная');?></li>
		<li><?=anchor('menu','Меню');?></li>
		<li><?=anchor('arenda-banketnogo-zala','Банкеты');?></li>
		<li><?=anchor('afisha','Афиша');?></li>
		<li><?=anchor('vakansii','Вакансии');?></li>
		<li><?=anchor('akcii','Акции');?></li>
		<li><?=anchor('contacts','Контакты');?></li>
	</ul>
</nav>